#!/bin/sh

cd ../lib
runhaskell Setup configure --user
runhaskell Setup build
runhaskell Setup install

cd ../test-bin
runhaskell Setup configure --user
runhaskell Setup build
runhaskell Setup install
